// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

// makesigmasemiPDRcppGSL
NumericMatrix makesigmasemiPDRcppGSL(NumericMatrix geno);
RcppExport SEXP _makesigmasemiPDRcppGSL_makesigmasemiPDRcppGSL(SEXP genoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type geno(genoSEXP);
    rcpp_result_gen = Rcpp::wrap(makesigmasemiPDRcppGSL(geno));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_makesigmasemiPDRcppGSL_makesigmasemiPDRcppGSL", (DL_FUNC) &_makesigmasemiPDRcppGSL_makesigmasemiPDRcppGSL, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_makesigmasemiPDRcppGSL(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
